# Generated by Django 3.2.16 on 2022-11-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=25)),
                ('passord1', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('time', models.CharField(max_length=23)),
                ('status', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'user_reg',
                'managed': False,
            },
        ),
    ]
