# Generated by Django 3.2.16 on 2022-11-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=25)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('complaint', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'complaint',
                'managed': False,
            },
        ),
    ]
